CREATE TABLE USUARIO (
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME   VARCHAR(256) NOT NULL,
    LASTNAME varchar(256) not null,
    USERNAME    VARCHAR(256) NOT NULL,
    EMAIL   VARCHAR(256) NOT NULL,
    PASSWORD   VARCHAR(256) NOT NULL,
    CREATION_DATE   DATETIME NOT NULL,
    LAST_DATE   DATETIME,
    AVATAR  TEXT,
    ROLE VARCHAR(50) NOT NULL

);